name: Security audit
on:
  push:
    paths:
      - "**/Cargo.*"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 2 * *" # 2nd day of month at 02:00
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
